name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger button

jobs:
  sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history for dates

    - name: Build React app
      run: |
        npm install
        npm run build

    - name: Generate sitemap from build folder
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://helxon.com/
        path-to-root: ./build
        include-pdf: true

    - name: Deploy to static hosting
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
